### ISSUE TITLE
color picker would save huge time 

### ISSUE THREAD

**Issue by OthmanAmoudi** [jvalen/pixel-art-react#12]
is there any way i can chose a color using rgb or #  ?

**Comment by jvalen** [comment]
Hi! @OthmanAmoudi, thanks for asking.
Seeing that the issue is closed already I understand that you found out the color picker has rgb and hex possible values.

I'm currently using react-color for the color-picker component. I may rethink that interaction since it could be not very intuitive.
Thanks again!
