### ISSUE TITLE
feature request: browser side gif rendering

### ISSUE THREAD

**Issue by bcho** [jvalen/pixel-art-react#15]
Hi, is that possible to render the grids to gif with https://github.com/jnordberg/gif.js ? With this way we can remove the server side rendering dependencies.

**Comment by bcho** [comment]
One possible way may be rendering each frame into canvas with given grid styles, then use the gif.js to render these canvas.

**Comment by jvalen** [comment]
Hi @bcho,
I've been thinking about that for a while, to reduce the image creation logic in the server side would be great, at least for downloading purposes. However, AFAIK if I want to tweet the image/gif I cannot generate its file in the client side, so I don't think I can get rid of the server logic easily.

I'll definitely explore the image generation in the client side asap, having in mind the browser support (since the library you provided use both File and Web Workers API).

I'll keep you posted @bcho

Thank you!

**Comment by jvalen** [comment]
Hi again @bcho 

That sounds great, I haven't tried your demo yet but it would be great if you send a pull request.
Could you create a feature branch over `develop` instead of `master` please (I've just synchronized `developed` :sweat_smile:).

Just a few things:
- Instead of adding the functionality inside the `Preview` component, you could try adding it within `DownloadDrawing` component. You'll find a `download` function that is triggered by an `onClick` button event. What do you think about it?

- Just out of curiosity, why did you choose `blob-stream` and `gif-encoder` over `gif.js` that was your original suggestion?

Thanks!
