### ISSUE TITLE
Import image frame or sprite sheet collection

### ISSUE THREAD

**Issue by gingerbeardman** [jvalen/pixel-art-react#43]
I'd like to be able to import a PNG file consisting of one frame, or a spritesheet consisting of multiple frames of identical size.

What do you think?

**Comment by jvalen** [comment]
Hi @gingerbeardman,

Sorry for the late reply :pray: . Here are some thoughts about the topic:

This feature has been in my mind for a while (I even have a working prototype) but I've had some foundational concerns though. Since the roots of the app are more focused on pushing creativity rather than modification of previous art, I haven't considered adding it before.

However, since you are asking for it and more people mentioned it as well, I might consider adding the feature, since it could be a very useful feature while still keeping the essence of the app.

The only constraints I would set are:
- All the image processing happen within the client side (zero server load)
- Max size for images: we could start with 50x50 pixels tops as initial version.

Are you thinking about sending a PR or asking for the feature?
I will be happy to work on it, as I mentioned before I had and old working prototype. But if you've worked already on it, please feel free open a pull request.

Thank you very much for raising this topic, I believe it could add good value to the app.

**Comment by gingerbeardman** [comment]
Hi, I was only asking.

No PR, sorry.
