### ISSUE TITLE
Why SimpleNotification component connected?

### ISSUE THREAD

**Issue by pke** [jvalen/pixel-art-react#5]
I wonder why the SimpleNotification component is connected? It does neither use state nor actions and could therefor be a "dumb" component. Or am I missing something?

**Comment by jvalen** [comment]
Hi @pke! Thanks for asking!

```SimpleNotification``` works in the following way:

1. A component send an action **SEND_NOTIFICATION** with the appropriate message.
2. The store creates a new state with the message.
3. The main app component send the notification in this state to the ```SimpleNotification``` component.
4. ```SimpleNotification``` render the messages and remove then sending an action **SEND_NOTIFICATION** with an empty string. Creating a new state with no notification messages.

I think because it sends an action is not a "dumb" component. I should remove ```mapStateToProps``` though because it doesn't use it.

Thanks!
